### ISSUE TITLE
chad scraper wouldn't use regex

### ISSUE THREAD

**Issue by 7ERr0r** [makindotcc/boringhyper#3]
![image](https://github.com/user-attachments/assets/6c42c297-cce7-4d9d-b9ce-a13592e0b35d)

He would write his own parser.

There are better tools than `regex` like `twoway`, `aho-corasick`, `quick_xml` or `serde_json`

**Comment by makindotcc** [comment]
i just prefer ``split()``, ``find()``, ``lines()``
